# Notebook to analize databased format from WP6

In [28]:
from pathlib import Path
import pandas as pd
import zipfile

In [14]:
FOLDER = Path(".")

## Investigate the EXCEL files

In [17]:
for path in FOLDER.iterdir():
    if path.suffix.lower() in [".xlsx", ".xls"]:
        print(f"\nEXCEL: {path.name}")
        xls = pd.ExcelFile(path)
        print("Sheets:", xls.sheet_names)

    elif path.suffix.lower() == ".csv":
        print(f"\nCSV: {path.name}")
        df = pd.read_csv(path, sep=None, engine="python", nrows=5)
        print("Columns:", list(df.columns))
        print(df.head())

EXCEL: 24ACE-FH-EARLY_DHM_v105_20260424.xls
Sheets: ['Data Handling Manual FH-EARLY']

EXCEL: 24ACE-FH-Early_import_DATA_20251015.xlsx
Sheets: ['Notice', 'INCLUSION', 'ML', 'Gene refseq', 'Family cardiovascular events']

## Inspect `Data Handling Manual FH-EARLY`
We have: 
* `Référence` that is the variable name
* `Type` that is the variable type
* `Format` that is the codes/rules
* `Intitulé` that is the label

In [22]:
file = Path("24ACE-FH-EARLY_DHM_v105_20260424.xls")

df = pd.read_excel(file, sheet_name="Data Handling Manual FH-EARLY")

print("Columns:")
for col in df.columns:
    print(f"- {col}")

print("\nFirst 10 rows:")
print(df)

Columns:
- Id
- Référence
- Saisie
- Type
- Format
- Intitulé

First 10 rows:
                                                   Id           Référence  \
0                                                 NaN                 NaN
1    INCLUSION (INC)   :  Patient identification (ID)                 NaN
2                                           ID102S2V9         PROJECTNAME
3                                                  V5                 SEX
4                                          ID102S2V10             BRTHDAT
..                                                ...                 ...
232                                       ID102S2V199            DATA_CNI
233                                       ID102S2V172            DATA_DT1
234                                       ID102S2V173           DATA_NUM2
235                                       ID102S2V183  RFINSTMOINS1MOISDT
236                                       ID102S2V203         DATA_INCLDT

    Saisie           Type                                             Format  \
0      NaN            NaN                                                NaN
1      NaN            NaN                                                NaN
2        O          Label                                                NaN
3        O  Radio buttons                              1 = Male \n2 = Female
4        O           Date  Précision = MM/YYYY\nValeurs par défaut = 01/0...
..     ...            ...                                                ...
232      O  Radio buttons                                   1 = Yes \n0 = No
233      O           Date  Précision = JJ/MM/YYYY\nValeurs par défaut = 0...
234      O         Entier                                         Taille : 2
235      O           Date  Précision = JJ/MM/YYYY\nValeurs par défaut = 0...
236      O           Date  Précision = JJ/MM/YYYY\nValeurs par défaut = 0...

                                              Intitulé
0                                                  NaN
1                                                  NaN
2                                             FH-Early
3                                               Gender
4                                        Date of birth
..                                                 ...
232    Tous les critères de non-inclusions sont à Non.
233  Calcul de la date de début de la prise des sta...
234                   Age de début de statine négativé
235                      Date d'inclusion moins 1 mois
236                           Date d'inclusion système

[237 rows x 6 columns]

### Investigate variables

In [23]:
variables = df[df["Référence"].notna()].copy()

variables = variables[["Id", "Référence", "Saisie", "Type", "Format", "Intitulé"]]

variables.to_csv("data_dictionary_clean.csv", index=False)

print(variables.head(20))
print(f"\nSaved {len(variables)} variables to data_dictionary_clean.csv")

             Id    Référence Saisie           Type  \
2     ID102S2V9  PROJECTNAME      O          Label
3            V5          SEX      O  Radio buttons
4    ID102S2V10      BRTHDAT      O           Date
5    ID102S2V11          AGE      O         Entier
6    ID102S2V15      INVNAME      O          Texte
7    ID102S2V12       SITEID      O          Texte
8    ID102S2V14  SUBJECT_REF      O          Texte
9    ID102S2V16      RFICDAT      O           Date
12   ID102S2V18       INF1YN      O  Radio buttons
13   ID102S2V19      INF1AYN      O  Radio buttons
14   ID102S2V20      INF1BYN      O  Radio buttons
15   ID102S2V21     INF1B1LS      O  Radio buttons
16   ID102S2V22     INF1B2DT      O           Date
17  ID102S2V182     INF1B5DT      O           Date
18   ID102S2V24     INF1B3DT      O           Date
19   ID102S2V25     INF1B4DT      O           Date
20   ID102S2V27    INF1B5NUM      O           Réel
21   ID102S2V34   INF1A1MESS      O          Label
24  ID102S2V205     CBCZ1AYN      O  Radio buttons
25  ID102S2V204      CBCZ1YN      O  Radio buttons

                                               Format  \
2                                                 NaN
3                               1 = Male \n2 = Female
4   Précision = MM/YYYY\nValeurs par défaut = 01/0...
5                     Taille : N\nMin = 18\nMax = 120
6                                          Taille : N
7                                          Taille : N
8                                          Taille : N
9   Précision = JJ/MM/YYYY\nValeurs par défaut = 0...
12                                   1 = Yes \n0 = No
13                                   1 = Yes \n0 = No
14                                   1 = Yes \n0 = No
15  1 = Information provided during a consultation...
16  Précision = JJ/MM/YYYY\nValeurs par défaut = 0...
17  Précision = JJ/MM/YYYY\nValeurs par défaut = 0...
18  Précision = JJ/MM/YYYY\nValeurs par défaut = 0...
19  Précision = JJ/MM/YYYY\nValeurs par défaut = 0...
20                                      Format : ##,#
21                                                NaN
24                                   1 = Yes \n0 = No
25                                   1 = Yes \n0 = No

                                             Intitulé
2                                            FH-Early
3                                              Gender
4                                       Date of birth
5                                                 Age
6                                        Investigator
7                                              Centre
8                                          Patient ID
9                                   Date of inclusion
12          Patient deceased at the time of inclusion
13  If so, did you verify that there was no object...
14  If not, has the patient been seen in the depar...
15                             Information procedures
16                                Date of information
17  Date of inclusion (i.e., date of collection of...
18  Date of sending of the NINO (note d'informatio...
19  Date of inclusion (i.e., one month after the d...
20                     Version of NINO sent/delivered
21                    Exclusion criteria n°1 violated
24  Agreement for the re-use of the biocollection ...
25  Agreement for both entry into the FH patient r...

Saved 201 variables to data_dictionary_clean.csv

In [26]:
variables = df[df["Référence"].notna()].copy()

variables = variables[["Id", "Référence", "Saisie", "Type", "Format", "Intitulé"]]

print("Variables:", len(variables))
variables.head(20)

Variables: 201

,Id,Référence,Saisie,Type,Format,Intitulé
2,ID102S2V9,PROJECTNAME,O,Label,NaN,FH-Early
3,V5,SEX,O,Radio buttons,1 = Male \n2 = Female,Gender
4,ID102S2V10,BRTHDAT,O,Date,Précision = MM/YYYY\nValeurs par défaut = 01/0...,Date of birth
5,ID102S2V11,AGE,O,Entier,Taille : N\nMin = 18\nMax = 120,Age
6,ID102S2V15,INVNAME,O,Texte,Taille : N,Investigator
7,ID102S2V12,SITEID,O,Texte,Taille : N,Centre
8,ID102S2V14,SUBJECT_REF,O,Texte,Taille : N,Patient ID
9,ID102S2V16,RFICDAT,O,Date,Précision = JJ/MM/YYYY\nValeurs par défaut = 0...,Date of inclusion
12,ID102S2V18,INF1YN,O,Radio buttons,1 = Yes \n0 = No,Patient deceased at the time of inclusion
13,ID102S2V19,INF1AYN,O,Radio buttons,1 = Yes \n0 = No,"If so, did you verify that there was no object..."
14,ID102S2V20,INF1BYN,O,Radio buttons,1 = Yes \n0 = No,"If not, has the patient been seen in the depar..."
15,ID102S2V21,INF1B1LS,O,Radio buttons,1 = Information provided during a consultation...,Information procedures
16,ID102S2V22,INF1B2DT,O,Date,Précision = JJ/MM/YYYY\nValeurs par défaut = 0...,Date of information
17,ID102S2V182,INF1B5DT,O,Date,Précision = JJ/MM/YYYY\nValeurs par défaut = 0...,"Date of inclusion (i.e., date of collection of..."
18,ID102S2V24,INF1B3DT,O,Date,Précision = JJ/MM/YYYY\nValeurs par défaut = 0...,Date of sending of the NINO (note d'informatio...
19,ID102S2V25,INF1B4DT,O,Date,Précision = JJ/MM/YYYY\nValeurs par défaut = 0...,"Date of inclusion (i.e., one month after the d..."
20,ID102S2V27,INF1B5NUM,O,Réel,"Format : ##,#",Version of NINO sent/delivered
21,ID102S2V34,INF1A1MESS,O,Label,NaN,Exclusion criteria n°1 violated
24,ID102S2V205,CBCZ1AYN,O,Radio buttons,1 = Yes \n0 = No,Agreement for the re-use of the biocollection ...
25,ID102S2V204,CBCZ1YN,O,Radio buttons,1 = Yes \n0 = No,Agreement for both entry into the FH patient r...

In [27]:
variables["Type"].value_counts(dropna=False)

Type
Radio buttons     68
Réel              39
Entier            24
Date              21
Combo box         21
Texte             12
Label              8
Cases à cocher     6
Tableau            2
Name: count, dtype: int64

## Analyze the mock export ZIP
> Saved the unzipped files in the folder `export-example`
> 
> The `*_ANSI.csv` file are mock patient data, exported from the real eCRF system.
> 
> They are meant to show the exact structure that we will receive later (June)
> 
> Now we need to compare the dictionary variable names vs the actual exported CSV columns!

In [34]:
zip_files = list(Path(".").glob("*.zip"))

# extract contents of ZIP files
# with zipfile.ZipFile("24ACE-FH-Early_export_exemple_20260424.zip") as zip_ref:
#    zip_ref.extractall(".")
export_folder = Path("export-example")

for f in export_folder.glob("*_ANSI.csv"):
    df_csv = pd.read_csv(f, sep=None, engine="python", encoding="latin1", nrows=5)
    print(f.name, df_csv.shape)
    print(list(df_csv.columns))
    print()

ML_ANSI.csv (5, 272)
['STUDY_ID', 'COUNTRY_ID', 'EXTRACTION_DATE', 'SITE_ID', 'SUBJECT_ID', 'SUBJECT_REF', 'REF_SITEID', 'REF_NUMBER', 'MODULE_ML', 'CD1TXT', 'CD2LS', 'CD3NUM', 'CD3NUM_V', 'CD4NUM', 'CD4NUM_V', 'CD5NUM', 'CD5NUM_V', 'CD6NUM', 'CD6NUM_V', 'CD7NUM', 'CD7NUM_V', 'CD8YN', 'CD8AYN', 'MH1YN', 'MH1ANUM', 'MH1ANUM_V', 'MH2YN', 'MH2ANUM', 'MH2ANUM_V', 'MH23NUM', 'MH23NUM_V', 'MH2BLS', 'MH3YN', 'MH3ANUM', 'MH3ANUM_V', 'MH4YN', 'MH4ANUM', 'MH4ANUM_V', 'MH5YN', 'MH5AYN', 'MH5A1NUM', 'MH5A1NUM_V', 'MH5BYN', 'MH5B1NUM', 'MH5B1NUM_V', 'MH5CYN', 'MH5C1NUM', 'MH5C1NUM_V', 'MH5DYN', 'MH5D1NUM', 'MH5D1NUM_V', 'MH5EYN', 'MH5E1NUM', 'MH5E1NUM_V', 'MH5FYN', 'MH5F1NUM', 'MH5F1NUM_V', 'MH5GYN', 'MH5HYN', 'MH16H1NUM', 'MH16H1NUM_V', 'MH16IYN', 'MH16I1NUM', 'MH16I1NUM_V', 'MH16JYN', 'MH16J1NUM', 'MH16J1NUM_V', 'MH16KYN', 'MH16K1NUM', 'MH16K1NUM_V', 'MH16LYN', 'MH16L1NUM', 'MH16L1NUM_V', 'FH1NUM', 'FH1NUM_V', 'FH2DT_D', 'FH2DT_M', 'FH2DT_Y', 'FH2DT', 'FH3YN', 'FH4YN', 'FH5YN', 'FH6YN', 'FH7YN', 'FH7ALS_C1', 'FH7ALS_C2', 'FH7ALS_C3', 'FH7ALS_C4', 'FH7ALS_C5', 'FH7ALS_C6', 'FH7ALS_C7', 'FH7ALS_C8', 'FH7ALS_C9', 'FH7ALS_C10', 'FH7ALS_C11', 'FH7ALS_C12', 'FH7ALS_C13', 'FH7ALS_C14', 'FH8YN', 'FH9YN', 'FH10NUM', 'FH10NUM_V', 'BS1YN', 'BS1ALS_C1', 'BS1ALS_C2', 'BS1ALS_C3', 'BS1ALS_C4', 'BS1A1TXT', 'BS3NUM', 'BS3NUM_V', 'BS3UNIT', 'BS4NUM', 'BS4NUM_V', 'BS4UNIT', 'BS5NUM', 'BS5NUM_V', 'BS5UNIT', 'BS6NUM', 'BS6NUM_V', 'BS6UNIT', 'BS7NUM', 'BS7NUM_V', 'BS7UNIT', 'BS8NUM', 'BS8NUM_V', 'BS8UNIT', 'BS9NUM', 'BS9NUM_V', 'BS10LS', 'BS8YN', 'BS8ADT_D', 'BS8ADT_M', 'BS8ADT_Y', 'BS8ADT', 'BS11NUM', 'BS11NUM_V', 'BS11UNIT', 'BS12NUM', 'BS12NUM_V', 'BS12UNIT', 'BS13NUM', 'BS13NUM_V', 'BS13UNIT', 'BS14NUM', 'BS14NUM_V', 'BS14UNIT', 'BS15NUM', 'BS15NUM_V', 'BS15UNIT', 'BS16NUM', 'BS16NUM_V', 'BS16UNIT', 'BS17NUM', 'BS17NUM_V', 'BS18LS', 'BS39LS_C0', 'BS39LS_C1', 'BS39LS_C2', 'BS39LS_C3', 'BS39LS_C4', 'BS39LS_C5', 'BS39LS_C6', 'BS39LS_C7', 'BS39LS_C8', 'BS39LS_C9', 'BS39ALS', 'BS19NUM', 'BS19NUM_V', 'BS20NUM', 'BS20NUM_V', 'BS21NUM', 'BS21NUM_V', 'BS22NUM', 'BS22NUM_V', 'BS23NUM', 'BS23NUM_V', 'BS24NUM', 'BS24NUM_V', 'BS25NUM', 'BS25NUM_V', 'BS26NUM', 'BS26NUM_V', 'BS27NUM', 'BS27NUM_V', 'BS28NUM', 'BS28NUM_V', 'BS29NUM', 'BS29NUM_V', 'BS30YN', 'BS30ADT_D', 'BS30ADT_M', 'BS30ADT_Y', 'BS30ADT', 'BS30BLS_C1', 'BS30BLS_C2', 'BS30BLS_C3', 'BS30BLS_C4', 'BS30BLS_C5', 'BS30BLS_C6', 'BS30BLS_C7', 'BS30BLS_C8', 'BS30BLS_C9', 'BS30BLS_C10', 'BS30CLS', 'BS34YN', 'BS34ALS', 'BS34A1TXT', 'BS34CNUM', 'BS34CNUM_V', 'BS34BNUM', 'BS34BNUM_V', 'BS35YN', 'BS35A1TXT', 'BS36YN', 'BS36ADT_D', 'BS36ADT_M', 'BS36ADT_Y', 'BS36ADT', 'BS36BNUM', 'BS36BNUM_V', 'BS36CNUM', 'BS36CNUM_V', 'BS37YN', 'BS37ADT_D', 'BS37ADT_M', 'BS37ADT_Y', 'BS37ADT', 'BS37BLS', 'BS37CNUM', 'BS37CNUM_V', 'BS37DNUM', 'BS37DNUM_V', 'BS38YN', 'BS38ADT_D', 'BS38ADT_M', 'BS38ADT_Y', 'BS38ADT', 'BS38BLS', 'BS38CNUM', 'BS38CNUM_V', 'BS38DNUM', 'BS38DNUM_V', 'BS38ENUM', 'BS38ENUM_V', 'BS38FNUM', 'BS38FNUM_V', 'TTT1YN', 'TTT2YN', 'TTT2ALS', 'TTT2BLS', 'TTT2CNUM', 'TTT2CNUM_V', 'TTT2DLS', 'TTT3LS_C1', 'TTT3LS_C2', 'TTT3LS_C3', 'TTT3LS_C4', 'TTT3LS_C5', 'TTT3LS_C6', 'TTT3LS_C7', 'TTT3LS_C8', 'TTT3LS_C9', 'TTT4LS_C1', 'TTT4LS_C2', 'TTT4LS_C3', 'TTT4LS_C4', 'TTT4LS_C5', 'TTT4LS_C6', 'TTT4LS_C7', 'VS1YN', 'VS1ALS', 'VS1BTXT']

TAB_BS_ANSI.csv (5, 20)
['STUDY_ID', 'COUNTRY_ID', 'EXTRACTION_DATE', 'SITE_ID', 'SUBJECT_ID', 'SUBJECT_REF', 'REF_SITEID', 'REF_NUMBER', 'MODULE_ML', 'FORM_BS', 'FORM_TAB_BS', 'TABBS1LS', 'TABBS2TXT', 'TABBS3TXT', 'TABBS5TXT', 'TABBS6DT_D', 'TABBS6DT_M', 'TABBS6DT_Y', 'TABBS6DT', 'TABBS4LS']

INC_ANSI.csv (5, 73)
['STUDY_ID', 'COUNTRY_ID', 'EXTRACTION_DATE', 'SITE_ID', 'SUBJECT_ID', 'SUBJECT_REF', 'REF_SITEID', 'REF_NUMBER', 'MODULE_INC', 'SEX', 'BRTHDAT_D', 'BRTHDAT_M', 'BRTHDAT_Y', 'BRTHDAT', 'AGE', 'AGE_V', 'INVNAME', 'SITEID', 'SUBJECT_REF_CL1', 'RFICDAT_D', 'RFICDAT_M', 'RFICDAT_Y', 'RFICDAT', 'INF1YN', 'INF1AYN', 'INF1BYN', 'INF1B1LS', 'INF1B2DT_D', 'INF1B2DT_M', 'INF1B2DT_Y', 'INF1B2DT', 'INF1B5DT_D', 'INF1B5DT_M', 'INF1B5DT_Y', 'INF1B5DT', 'INF1B3DT_D', 'INF1B3DT_M', 'INF1B3DT_Y', 'INF1B3DT', 'INF1B4DT_D', 'INF1B4DT_M', 'INF1B4DT_Y', 'INF1B4DT', 'INF1B5NUM', 'INF1B5NUM_V', 'CBCZ1AYN', 'CBCZ1YN', 'CB1YN', 'CB2DT_D', 'CB2DT_M', 'CB2DT_Y', 'CB2DT', 'CB3DT_D', 'CB3DT_M', 'CB3DT_Y', 'CB3DT', 'CB4YN', 'CB5YN', 'CSTPT1DT_D', 'CSTPT1DT_M', 'CSTPT1DT_Y', 'CSTPT1DT', 'CSTTR1YN', 'CSTTR1AYN', 'CICZ1YN', 'CIFR1YN', 'CIFR2YN', 'CIFR3YN', 'CNIFR1YN', 'CIPT1YN', 'CIPT2YN', 'CITR1YN', 'CITR2YN']

TAB_FH_ANSI.csv (5, 16)
['STUDY_ID', 'COUNTRY_ID', 'EXTRACTION_DATE', 'SITE_ID', 'SUBJECT_ID', 'SUBJECT_REF', 'REF_SITEID', 'REF_NUMBER', 'MODULE_ML', 'FORM_FH', 'FORM_TAB_FH', 'TABFH1LS', 'TABFH1ATXT', 'TABFH2LS', 'TABFH3NUM', 'TABFH3NUM_V']

## Inspect `INC_ANSI.csv`
### For each variable in the dictionary, what columns appear in the export CSV? 
> For instance: 
> * `BRTHDAT` in dictionary became `BRTHDAT_D, BRTHDAT_M, BRTHDAT_Y, BRTHDAT` in .csv (as also mentioned in Alain email)

In [39]:
inc = pd.read_csv(export_folder / "INC_ANSI.csv", encoding="latin1", sep=";")
inc_cols = inc.columns.tolist()
print(inc.shape)

for var in ["SEX", "BRTHDAT", "AGE", "RFICDAT"]:
    matches = [c for c in inc_cols if c.startswith(var)]
    print(var, "->", matches)

# automate what above 
inc_matches = variables.copy()

inc_matches["export_columns"] = inc_matches["Référence"].apply(
    lambda var: [c for c in inc.columns if c.startswith(str(var))]
)

inc_matches[["Référence", "Type", "Intitulé", "export_columns"]].head(30)

(5, 73)
SEX -> ['SEX']
BRTHDAT -> ['BRTHDAT_D', 'BRTHDAT_M', 'BRTHDAT_Y', 'BRTHDAT']
AGE -> ['AGE', 'AGE_V']
RFICDAT -> ['RFICDAT_D', 'RFICDAT_M', 'RFICDAT_Y', 'RFICDAT']

,Référence,Type,Intitulé,export_columns
2,PROJECTNAME,Label,FH-Early,[]
3,SEX,Radio buttons,Gender,[SEX]
4,BRTHDAT,Date,Date of birth,"[BRTHDAT_D, BRTHDAT_M, BRTHDAT_Y, BRTHDAT]"
5,AGE,Entier,Age,"[AGE, AGE_V]"
6,INVNAME,Texte,Investigator,[INVNAME]
7,SITEID,Texte,Centre,[SITEID]
8,SUBJECT_REF,Texte,Patient ID,"[SUBJECT_REF, SUBJECT_REF_CL1]"
9,RFICDAT,Date,Date of inclusion,"[RFICDAT_D, RFICDAT_M, RFICDAT_Y, RFICDAT]"
12,INF1YN,Radio buttons,Patient deceased at the time of inclusion,[INF1YN]
13,INF1AYN,Radio buttons,"If so, did you verify that there was no object...",[INF1AYN]
14,INF1BYN,Radio buttons,"If not, has the patient been seen in the depar...",[INF1BYN]
15,INF1B1LS,Radio buttons,Information procedures,[INF1B1LS]
16,INF1B2DT,Date,Date of information,"[INF1B2DT_D, INF1B2DT_M, INF1B2DT_Y, INF1B2DT]"
17,INF1B5DT,Date,"Date of inclusion (i.e., date of collection of...","[INF1B5DT_D, INF1B5DT_M, INF1B5DT_Y, INF1B5DT]"
18,INF1B3DT,Date,Date of sending of the NINO (note d'informatio...,"[INF1B3DT_D, INF1B3DT_M, INF1B3DT_Y, INF1B3DT]"
19,INF1B4DT,Date,"Date of inclusion (i.e., one month after the d...","[INF1B4DT_D, INF1B4DT_M, INF1B4DT_Y, INF1B4DT]"
20,INF1B5NUM,Réel,Version of NINO sent/delivered,"[INF1B5NUM, INF1B5NUM_V]"
21,INF1A1MESS,Label,Exclusion criteria n°1 violated,[]
24,CBCZ1AYN,Radio buttons,Agreement for the re-use of the biocollection ...,[CBCZ1AYN]
25,CBCZ1YN,Radio buttons,Agreement for both entry into the FH patient r...,[CBCZ1YN]
28,CB1YN,Radio buttons,« Consentement pour l'examendes caractéristiqu...,[CB1YN]
29,CB2DT,Date,Date of signature of consent,"[CB2DT_D, CB2DT_M, CB2DT_Y, CB2DT]"
30,CB3DT,Date,Date of consent signature - prospective patients,"[CB3DT_D, CB3DT_M, CB3DT_Y, CB3DT]"
31,CB4YN,Radio buttons,Agreement for the re-use of the biocollection ...,[CB4YN]
32,CB5YN,Radio buttons,Agreement for both entry into the FH patient r...,[CB5YN]
33,CB1A1MESS,Label,Inclusion criteria n°3 violated,[]
36,CSTPT1DT,Date,Date of consent signature,"[CSTPT1DT_D, CSTPT1DT_M, CSTPT1DT_Y, CSTPT1DT]"
39,CSTTR1YN,Radio buttons,Agreement for both entry into the FH patient r...,[CSTTR1YN]
40,CSTTR1AYN,Radio buttons,Agreement for the re-use of the biocollection ...,[CSTTR1AYN]
43,CICZ1YN,Radio buttons,Patient suspected or confirmed for FH,[CICZ1YN]

In [40]:
inc[["SUBJECT_REF", "SUBJECT_REF_CL1"]].head()

  SUBJECT_REF SUBJECT_REF_CL1
0   ZZOI-0001       ZZOI-0001
1   QGYD-0002       QGYD-0002
2    EJI-0003        EJI-0003
3     CH-0004         CH-0004
4   UHVT-0005       UHVT-0005

In [42]:
# check one radio buttons (for sex 1 is male and 2 female)
inc["SEX"].value_counts(dropna=False)

SEX
1.0    2
2.0    2
NaN    1
Name: count, dtype: int64

In [43]:
# check yes/no radio fields
inc["INF1YN"].value_counts(dropna=False)

INF1YN
0    5
Name: count, dtype: int64

In [45]:
# check date fields
# difference bewtween NaN and ND: Nan means missing data, ND means not determined
inc[["BRTHDAT_D", "BRTHDAT_M", "BRTHDAT_Y", "BRTHDAT"]].head()

   BRTHDAT_D BRTHDAT_M  BRTHDAT_Y  BRTHDAT
0        NaN         7     1997.0      NaN
1        NaN         6     2007.0      NaN
2        NaN       NaN        NaN      NaN
3        NaN         4     1978.0      NaN
4        NaN        ND     1972.0      NaN

In [46]:
# check a complete date field
inc[["RFICDAT_D", "RFICDAT_M", "RFICDAT_Y", "RFICDAT"]].head()

   RFICDAT_D  RFICDAT_M  RFICDAT_Y     RFICDAT
0         20          2       2013  20/02/2013
1         17          2       1989  17/02/1989
2         22          9       1971  22/09/1971
3          5          5       2008  05/05/2008
4         27         12       2009  27/12/2009

In [47]:
# check numeric variables
inc[["AGE", "AGE_V"]].head()

   AGE  AGE_V
0   15     15
1   18     18
2   59     59
3   30     30
4   37     37

In [48]:
# check a numeric field that may have missing 
inc[["INF1B5NUM", "INF1B5NUM_V"]].head()

   INF1B5NUM  INF1B5NUM_V
0        NaN          NaN
1        1.2          1.2
2        NaN          NaN
3        NaN          NaN
4        NaN          NaN

## Inspect `ML_ANSI.csv`
### How to handle checkbox variables
> `INC_ANSI.csv` do not contain checkbox examples, but Alain warned that checkbox variables are transformed differently
> 
> A checkbox variable allow selecting multiple answer simultaneosly. Something as: Which sympthoms? 
> * [] fever
> * [] cough
> * [] headache
> In the email they said that checkbox variable become: `Variable_C1`, `Variable_C2`, `Variable_C3`...
> 
> And in `ML_ANSI.csv` investigation we saw: `FH7ALS_C1`, `FH7ALS_C2`, `FH7ALS_C3`...

In [51]:
# confirm theory from dictionary
variables[variables["Référence"] == "FH7ALS"]

,Id,Référence,Saisie,Type,Format,Intitulé
121,ID102S2V86,FH7ALS,O,Cases à cocher,1 = Mother \n2 = Father \n3 = child \n4 = sibl...,If yes: specify

In [50]:
ml = pd.read_csv(export_folder / "ML_ANSI.csv", encoding="latin1", sep=";")
checkbox_cols = [c for c in ml.columns if c.startswith("FH7ALS_C")]
print(checkbox_cols)
ml[checkbox_cols].head()

['FH7ALS_C1', 'FH7ALS_C2', 'FH7ALS_C3', 'FH7ALS_C4', 'FH7ALS_C5', 'FH7ALS_C6', 'FH7ALS_C7', 'FH7ALS_C8', 'FH7ALS_C9', 'FH7ALS_C10', 'FH7ALS_C11', 'FH7ALS_C12', 'FH7ALS_C13', 'FH7ALS_C14']

,FH7ALS_C1,FH7ALS_C2,FH7ALS_C3,FH7ALS_C4,FH7ALS_C5,FH7ALS_C6,FH7ALS_C7,FH7ALS_C8,FH7ALS_C9,FH7ALS_C10,FH7ALS_C11,FH7ALS_C12,FH7ALS_C13,FH7ALS_C14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN